x-airflow-common: &airflow-common
  build:
    context: ..
    args:
      EXTRA_REQUIREMENTS: ${EXTRA_REQUIREMENTS}
  env_file:
    - ../.env
  volumes:
    - airflow_logs:/opt/airflow/logs
    - airflow_config:/opt/airflow/config
    - airflow_plugins:/opt/airflow/plugins
    - ../pipelines:/opt/pipelines
  user: "${AIRFLOW_UID:-50000}:0"

x-worker-hosts: &worker-hosts
  extra_hosts:
    - "airflow-worker:10.0.2.120"
    - "worker1:10.0.2.120"
    - "worker2:10.0.2.8"
    - "worker3:10.0.2.123"

services:

  airflow-apiserver:
    <<: [*airflow-common, *worker-hosts]
    environment:
      - PYTHONPATH=${PYTHONPATH}
    command: airflow api-server
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      airflow-init:
        condition: service_completed_successfully

  airflow-scheduler:
    <<: [*airflow-common, *worker-hosts]
    environment:
      - PYTHONPATH=${PYTHONPATH}
    command: scheduler
    restart: always
    depends_on:
      airflow-init:
        condition: service_completed_successfully

  airflow-dag-processor:
    <<: *airflow-common
    environment:
      - PYTHONPATH=${PYTHONPATH}
    command: dag-processor
    restart: always
    depends_on:
      airflow-init:
        condition: service_completed_successfully

  airflow-triggerer:
    <<: *airflow-common
    environment:
      - PYTHONPATH=${PYTHONPATH}
    command: triggerer
    restart: always
    depends_on:
      airflow-init:
        condition: service_completed_successfully

  airflow-init:
    <<: *airflow-common
    environment:
      - PYTHONPATH=${PYTHONPATH}
    entrypoint: /bin/bash
    user: "0:0"
    command:
      - -c
      - |
        mkdir -p /opt/airflow/{logs,dags,plugins,config}
        chown -R "${AIRFLOW_UID}:0" /opt/airflow/
        /entrypoint airflow db migrate
        /entrypoint airflow pools set spark_jobs_pool 4 "Pool for Spark Submit jobs"

  airflow-cli:
    <<: *airflow-common
    environment:
      - PYTHONPATH=${PYTHONPATH}
      - SPARK_HOME=/opt/spark
      - PATH=/opt/spark/bin:/home/airflow/.local/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games
    profiles:
      - debug
    command:
      - bash
      - -c
      - airflow

  flower:
    <<: [*airflow-common, *worker-hosts]
    environment:
      - PYTHONPATH=${PYTHONPATH}
    command: celery flower
    ports:
      - "5555:5555"
    restart: always
    depends_on:
      airflow-init:
        condition: service_completed_successfully

volumes:
  airflow_logs:
  airflow_config:
  airflow_plugins: